let a=10;
console.log('value of A${a}');
letb=20;
console.log('value of B${b}');

// 2) code

try{
let a=10;
console.log('value of A${a}');
letb=20;
console.log('value of B${b}');
}catch(err){
  console.log("Error found");
}

// 3) code


try{
    let a=10;
    console.log(`Value of A${a}`);
    letb=50;
    console.log(`Value of B${b}`);
}catch(err){
    console.log("Error Found");
    console.log(err.name);
    console.log(err.message);
    console.log(err.stack);
}

// 4) code

let a=8;
let ageErr = new Error("Invalid Age");
try{
    if(a<18){
        throw ageErr;
    }else{
        console.log("Valid age");
    }
}catch(err){
    console.log(err.message);
}

// 5) code

let a=8;
let ageErr = new Error("Invalid Age");
try{
    if(a<18){
        throw ageErr;
    }else{
        console.log("Valid age");
    }
}catch(err){
    console.log(err.message);
}

// 6) code

let a=8
try{
    if(a<18){
        throw new TypeError("Invalid Age");
    }else{
        console.log("Valid age");
    }
}catch(err){
    console.log(err.name)
    console.log(err.message);
}

// 7) code
let a=8;
try{
    if(a<18){
        throw new TypeError("Invalid Age");
    }else{
        console.log("Valid age");
    }
}catch(err){
    console.log(err.name)
    console.log(err.message);
}finally{
    console.log("Finally code");
}

